spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-34.railway.app:7370/postgres?currentSchema=public
    #url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}?currentSchema=public
    #username: ${DEV_DB_USERNAME}
    #password: ${DEV_DB_PASSWORD}
    username: postgres
    password: VinkhgAYd1TP5iRCrQtN
    name: climby-api

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes