
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: climby-api
    description: It is an api-rest for a climbing project.
    author: Edu Gomez
    version: '@project.version@'
spring:
  profiles:
    active: dev