spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-34.railway.app:7370/postgres?currentSchema=public
    username: postgres
    password: VinkhgAYd1TP5iRCrQtN
    name: spring-blog

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes